### ISSUE TITLE
Deploying with Swift 3.0-preview-1 fails

### ISSUE THREAD

**Issue by culturedlabs** [kylef/heroku-buildpack-swift#14]
I'm trying to deploy to Heroku:
Is this a bug or has the buildpack no support for Swift 3.0?

> -----> Fetching set buildpack https://github.com/kylef/heroku-buildpack-swift.git... Done
> -----> Swift app detected
> Cloning into 'swiftenv'...
> -----> Installing 3.0-preview-1
> We don't have build instructions for 3.0-preview-1.
>  !     Push rejected, failed to compile Swift app

**Comment by kylef** [comment]
This should be fixed by 7c66463, can you please confirm this works for you.

**Comment by culturedlabs** [comment]
Works for me. Thanks!
