### ISSUE TITLE
Allow the app powered by Swift Package Manager to not be in the root directory. 

### ISSUE THREAD

**Issue by steprescott** [kylef/heroku-buildpack-swift#17]
This is a feature request rather than an issue but would it be possible to supply a flag that will allow the repo to specify where the project that is powered by Swift Package Manager is located.

My example is I have an iOS app and within that folder structure there is the iOS app at the root and then the API (written in Swift) is in a sub directory of the root `/API`. It is in this `/API` directory that the app with the `Package.swift` file is located.

Is this possible?

When I try to use your buldpack, Heroku fails with 

```
Failed to detect set buildpack https://github.com/kylef/heroku-buildpack-swift.gi
```

**Comment by kylef** [comment]
I don't plan to support this because it would add a lot of complexity and would also make the build pack inconsistent with every other Heroku buildpack.
