### ISSUE TITLE
 fatal error: 'uuid/uuid.h' file not found

### ISSUE THREAD

**Issue by gtchance** [kylef/heroku-buildpack-swift#19]
Any idea what could cause this?
```
Compile LinuxBridge LinuxBridge.c
In file included from /tmp/.../Packages/LinuxBridge-2.0.1/LinuxBridge/LinuxBridge.c:2:
/tmp/.../Packages/LinuxBridge-2.0.1/LinuxBridge/include/LinuxBridge.h:6:10: fatal error: 'uuid/uuid.h' file not found
#include <uuid/uuid.h>
```

I have been unable to find anything about it anywhere.

**Comment by mmyyccrroo** [comment]
@gtchance, I found 2 references to this problem in Perfect JIRA (free registration required):
http://jira.perfect.org:8080/browse/ISS-124
http://jira.perfect.org:8080/browse/ISS-118.

The suggested solution was to `apt-get install uuid-dev`, but I am not sure how to include that in the buildback.

**Comment by kylef** [comment]
You can install any packages you one in the `pre_compile` hook. You can place a script in `bin/pre_compile` inside your repository and the buildpack will execute it before compiling your sources.

```bash
#!/usr/bin/env bash

apt-get install uuid-dev
```

**Comment by kylef** [comment]
The problem is with compiling your `LinuxBridge` dependency and doesn't seem to be any problem with the build pack itself. I'd reach out to the maintainers of that library regarding how to use this dependency. You may need to ensure that any of its dependencies are installed such as via the `pre_compile` hook.

**Comment by jarrodparkes** [comment]
I've run into the same issue trying to get my application to build which relies on https://github.com/PerfectlySoft/Perfect-Crypto. using the pre_compile script that @kylef recommended above, I get the following out:

```
-----> Running pre-compile hook
W: Not using locking for read only lock file /var/lib/dpkg/lock
E: Unable to write to /var/cache/apt/
E: The package lists or status file could not be parsed or opened.
 !     Push rejected, failed to compile Swift app.
 !     Push failed
```

Here are the contents of the `bin/pre_compile`:

```bash
#!/usr/bin/env bash

apt-get install uuid-dev
```

Any suggestions on a workaround?

**Comment by MithunReddy** [comment]
@gtchance did you find any workaround for this?

**Comment by rchatham** [comment]
@jarrodparkes I'm getting the same issue after trying to upgrade to current Swift, based in part on your solutions from Udacity.
 
I have the `apt-get install uuid-dev` line in the Dockerfile, but when trying to run apt-get from the shell I get the following:
```
$ sudo apt-get install uuid-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package uuid-dev
```

Any solutions for this?

**Comment by WesleyBatista** [comment]
I use Ubuntu 17.10 and had the same issue. 

The sudo `apt-get install uuid-dev` helped. But then I had other dependencies problems like [this](https://answers.launchpad.net/mosquitto/+question/645926)

The final command that I would recommend is this: 

`sudo apt-get install xsltproc docbook-xsl uuid-dev`

**Comment by xcnix** [comment]
for RHEL 
yum install libuuid libuuid-devel

**Comment by awasthi027** [comment]
remote: In file included from /tmp/build_76fc57fa28a1232e00a22b4592e0f911/.build/checkouts/Perfect-LinuxBridge/Sources/LinuxBridge/LinuxBridge.c:2:
remote: /tmp/build_76fc57fa28a1232e00a22b4592e0f911/.build/checkouts/Perfect-LinuxBridge/Sources/LinuxBridge/include/LinuxBridge.h:6:10: fatal error: 'uuid/uuid.h' file not found
remote: #include <uuid/uuid.h>
remote:          ^~~~~~~~~~~~~
remote: 1 error generated.
remote: [4/21] Compiling LinuxBridge LinuxBridge.c
remote: [5/21] Compiling c-atomics.c
remote:  !     Push rejected, failed to compile Swift app.

**Comment by pwnchief** [comment]
Ensure to run a 
`apt-get update` 
before
`apt-get install uuid-dev`

**Comment by tonykingnz** [comment]
> @gtchance, I found 2 references to this problem in Perfect JIRA (free registration required):
> http://jira.perfect.org:8080/browse/ISS-124
> http://jira.perfect.org:8080/browse/ISS-118.
> 
> The suggested solution was to `apt-get install uuid-dev`, but I am not sure how to include that in the buildback.

That worked for me, thanks. I was using the Docker image of Swift (swift:5.3.2-bionic) to run perfect.org I simple runned the command `apt-get install uuid-dev` and worked fine
