### ISSUE TITLE
Error: Unable to set buildpack https://github.com/vapor/heroku-buildpack

### ISSUE THREAD

**Issue by jjessel** [kylef/heroku-buildpack-swift#21]
When I try to deploy to Heroku, I get the following error 

Error: Unable to set buildpack https://github.com/vapor/heroku-buildpack:  ▸    Couldn't find that app.

I have tried setting the buildpack via the buildpacks:set command and same error.

**Comment by kylef** [comment]
I think this error indicates that you didn't run the `buildpacks:set` command from a Heroku app. You can add the `-a <appname>` option to specify an application.

**Comment by jjessel** [comment]
I tried that too and got the same error. I was initially able to use `vapor heroku init` and it built the app. I had to delete the app from Heroku ran the command again. That's when I see the error.

**Comment by kylef** [comment]
> I had to delete the app from Heroku ran the command again

So you are trying to set the build pack for a deleted Heroku app?

**Comment by jjessel** [comment]
I deleted the app from Heroku and ran `vapor heroku init` again. That's when I get the error. If, after the app is deleted, I try to set the buildpack, I get the same error. If I use the create command and push the changes to Heroku, it builds fine.

**Comment by kylef** [comment]
>  If, after the app is deleted, I try to set the buildpack, I get the same error

You can't set a build pack for a deleted app, because the app doesn't exist. Not sure what you expect this to actually achieve.

**Comment by jjessel** [comment]
I thought after deleting my app, that vapor heroku init would create a new app for me. Instead I kept getting the error.

**Comment by kylef** [comment]
I don't know what `vapor heroku init` is, this is the issue tracker for a Heroku Swift build pack and no vapour.

You can create a Heroku app with the Heroku Swift buildpack using the following:

```shell
$ heroku create --buildpack https://github.com/kylef/heroku-buildpack-swift.git
```

If you have an existing Heroku app, you can set the build pack using:

```
$ heroku buildpacks:set https://github.com/kylef/heroku-buildpack-swift.git --app <my app name>
```

**Comment by jjessel** [comment]
Ok. Got it. Thanks.

**Comment by eligreg** [comment]
@jjessel how did you end up solving this issue? I'm experiencing the same.
