### ISSUE TITLE
Failed to detect build pack

### ISSUE THREAD

**Issue by philipengberg** [kylef/heroku-buildpack-swift#22]
This seems like a novice error, but my search around the web and this repository didn't provide any solutions.

I've set the build pack using 

```
> heroku create --buildpack https://github.com/kylef/heroku-buildpack-swift.git
Creating app... done, ⬢ polar-harbor-76973
Setting buildpack to https://github.com/kylef/heroku-buildpack-swift.git... done
https://polar-harbor-76973.herokuapp.com/ | https://git.heroku.com/polar-harbor-76973.git
```

When I then run `git push heroku master` I just get 

```
remote: -----> Failed to detect set buildpack https://github.com/kylef/heroku-buildpack-swift
```

Any suggestions?

**Comment by kylef** [comment]
@philipengberg Do you have a `Package.swift` in the root of your repository you are trying to push to Heroku?
