### ISSUE TITLE
Cannot invoke executable by its name on Swift 4

### ISSUE THREAD

**Issue by adtrevor** [kylef/heroku-buildpack-swift#31]
Using the buildpack with Swift 4, it isn't possible to execute a program by directly calling its name in the procfile.

This may be because of this:

> In Swift 4, the Swift Package Manager will build to a different path, containing a platform sub-folder (.build/macosx-x86_64/debug for mac and .build/linux-x86_64/debug for linux), making it more cumbersome to run the executable from the command line.
[SE-179 Swift `run` Command](https://github.com/apple/swift-evolution/blob/master/proposals/0179-swift-run-command.md)

Thank you !

Trevör

EDIT : 
Both `.build/linux-x86_64/release/MyExecutableName` and `.build/linux-x86_64/debug/MyExecutableName` don't let me run the execuable either, does your buildpack remove the .build folder ?

**Comment by kheinrich188** [comment]
https://stackoverflow.com/questions/46420691/slackbot-written-in-swift-4-deployed-on-heroku Maybe a problem also with swift 4.0 ? Arg cannot run the app successfully

**Comment by kylef** [comment]
I am seeing Swift 4.0 setting up the symbolic link from the existing name and thus this still should work.

```
$ ls -al .build
lrwxr-xr-x   1 kyle  staff     30 27 Sep 10:10 debug -> x86_64-apple-macosx10.10/debug
drwxr-xr-x   3 kyle  staff    102 27 Sep 10:10 x86_64-apple-macosx10.10
```

---

@adtrevor The binaries and necessary libraries are moved over to the final Heroku slug and available under the `PATH`. You should just use the binary name in the Procfile, for example:

```
web: MyExecutableName --workers 5 --bind 0.0.0.0:$PORT
```

@kheinrich188 Looks like that tutorial is also incorrect and setting the Procfile incorrectly. Should be something like:

```
web: robot-or-not-bot
```

**Comment by adtrevor** [comment]
I will try it again, maybe I did an error last time but it didn't worked !

**Comment by kylef** [comment]
https://github.com/kylef/heroku-buildpack-swift/commit/d7f0218064d3448dedd8e796a4669bf6126a9d57 fixes problems while copying over  the binaries and dynamic libraries. However there is another problem with Swift 4 and the heroku-16 stack (you can possibly work around the problem by temporarily using cedar-14. Tracked via: https://github.com/kylef/heroku-buildpack-swift/issues/32

**Comment by kylef** [comment]
5e91d32db352a0a28f628f856525924caf738adc adds support for heroku-16 stack. Please try everything again.

**Comment by JeromeCHA** [comment]
I still get the error with the lastest version and swift 4.2 and heroku-16

```
➜  slackBot git:(master) heroku run:detached slackbot
Running slackbot on ⬢ slack-bot... done, run.3646 (Free)
Run heroku logs --app slack-bot --dyno run.3646 to view the output.
➜  slackBot git:(master) heroku logs --app slack-bot --dyno run.3646
2018-10-31T16:49:02.466717+00:00 heroku[run.3646]: Starting process with command `.build/release/slack-bot`
2018-10-31T16:49:03.162037+00:00 heroku[run.3646]: State changed from starting to up
2018-10-31T16:49:06.044276+00:00 heroku[run.3646]: State changed from up to complete
2018-10-31T16:49:06.025404+00:00 heroku[run.3646]: Process exited with status 127
2018-10-31T16:49:05.946164+00:00 app[run.3646]: bash: .build/release/slack-bot: No such file or directory
```
