### ISSUE TITLE
H12 Request Timeout

### ISSUE THREAD

**Issue by EmperiorEric** [kylef/heroku-buildpack-swift#38]
We installed https://github.com/httpswift/swifter using this build pack but things aren't quite right. The build seems to be completing but requests aren't actually working. They are timing out.

Not sure if this is Swifter or a setting we don't understand. Its working locally so maybe we've just failed to set something up in Heroku just right?

**Comment by kylef** [comment]
Hi @EmperiorEric, could you please provide a bit more details such as the contents of your Procfile. I wonder if it is a problem with PORT configuration.

If your repository is OSS then link to it would be great so I can debug.
