### ISSUE TITLE
Could you support swift 4.1?

### ISSUE THREAD

**Issue by rafiki270** [kylef/heroku-buildpack-swift#39]

**Comment by kylef** [comment]
Once Swift 4.1 is released, it should work right away with the build pack. If you want to test any of the snapshots that will already work by setting the swift version to one of them (see https://github.com/kylef/heroku-buildpack-swift#specify-a-swift-version), for example `4.1-DEVELOPMENT-SNAPSHOT-2018-02-21-a`.
