### ISSUE TITLE
Getting Error SIGSEGV

### ISSUE THREAD

**Issue by pshrinivas** [kylef/heroku-buildpack-swift#40]
Whenever I try to `heroku create --buildpack <https git url>` 
getting error : !    error getting commands pid 7930 SIGSEGV (signal 11)

Similarly while doing `vapor heroku init` getting error : 
Error: Unable to create Heroku app: !    error getting commands pid 7325 SIGSEGV (signal 11)

running on macos high sierra 10.13.6

**Comment by kylef** [comment]
If your `heroku` comamnd is segfaulting that is not an issue with the buildpack but the heroku cli itself, check that you installed it correctly and reach out to Heroku support for support for their CLI if you're stuck.
