### ISSUE TITLE
Kitura on Heroku

### ISSUE THREAD

**Issue by joaoamaral** [kylef/heroku-buildpack-swift#5]
Hi! I'm building a Kitura app and I want to deploy it to Heroku
I'm using DEVELOPMENT-SNAPSHOT-2016-03-24-a and using this buildpack

but I found this error about Dispatch module while compiling KituraSys
can someone give me some help? Thank you :)

```
remote: Compiling KituraSys
remote: /tmp/build_daf57757ad8192bb59b6c59bc2bc27a3/Packages/Kitura-Sys-0.7.0/Sources/KituraSys/SysUtils.swift:17:8: error: no such module 'Dispatch'
remote: import Dispatch
remote:        ^
remote: 
<unknown>:0: error: build had 1 command failures
remote: swift-build: error: exit(1): /app/tmp/cache/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-03-24-a/usr/bin/swift-build-tool -f /tmp/build_daf57757ad8192bb59b6c59bc2bc27a3/.build/release.yaml default
```

**Comment by kylef** [comment]
@joaoamaral As mentioned in Kitura's installation instructions, you will need to install dependencies including Dispatch: https://github.com/IBM-Swift/Kitura#installation-linux-apt-based

If you place a script at `bin/pre_compile` and  `bin/post_compile`, where you can run commands such as these to install the dependencies.
