### ISSUE TITLE
Build fails for swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a

### ISSUE THREAD

**Issue by LanceWithWang** [kylef/heroku-buildpack-swift#6]
LanceiMacWiFi:vapor-swift-lance meixiandongpinshangcheng$ git push heroku master
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (9/9), 954 bytes | 0 bytes/s, done.
Total 9 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching set buildpack https://github.com/kylef/heroku-buildpack-swift... done
remote: -----> Swift app detected
remote: Cloning into 'swiftenv'...
remote: -----> Installing DEVELOPMENT-SNAPSHOT-2016-02-08-a
remote: Downloading https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a-ubuntu14.04.tar.gz
remote: DEVELOPMENT-SNAPSHOT-2016-02-08-a has been installed.
remote: -----> Installing clang-3.7.0
remote: -----> Building Package
remote: Cloning https://github.com/qutheory/vapor.git
remote: Using version 0.5.3 of package vapor
remote: Cloning https://github.com/swiftx/s4.git
remote: Using version 0.2.1 of package s4
remote: Cloning https://github.com/SwiftX/C7.git
remote: Using version 0.2.0 of package C7
remote: Cloning https://github.com/Zewo/String.git
remote: Using version 0.4.3 of package String
remote: Cloning https://github.com/Zewo/OS.git
remote: Using version 0.4.2 of package OS
remote: Cloning https://github.com/Zewo/JSON.git
remote: Using version 0.4.2 of package JSON
remote: Cloning https://github.com/Zewo/InterchangeData.git
remote: Using version 0.4.3 of package InterchangeData
remote: Cloning https://github.com/Zewo/Data.git
remote: Using version 0.4.9 of package Data
remote: Cloning https://github.com/qutheory/Hummingbird.git
remote: /tmp/build_37bf4ccdf1edc5c49a72e2add8982a0f/Packages/Hummingbird/Package.swift:16:11: error: use of unresolved identifier 'Product'
remote: let lib = Product(name: "Hummingbird", type: .Library(.Dynamic), modules: "Hummingbird")
remote:           ^~~~~~~
remote: /tmp/build_37bf4ccdf1edc5c49a72e2add8982a0f/Packages/Hummingbird/Package.swift:17:1: error: use of unresolved identifier 'products'
remote: products.append(lib)
remote: ^~~~~~~~
remote: Using version 2.0.0 of package Hummingbird
remote: Cloning https://github.com/CryptoKitten/HMAC.git
remote: Using version 0.3.1 of package HMAC
remote: Cloning https://github.com/CryptoKitten/CryptoEssentials.git
remote: Using version 0.2.1 of package CryptoEssentials
remote: Cloning https://github.com/CryptoKitten/SHA2.git
remote: /tmp/build_37bf4ccdf1edc5c49a72e2add8982a0f/Packages/Hummingbird-2.0.0/Package.swift:16:11: error: use of unresolved identifier 'Product'
remote: let lib = Product(name: "Hummingbird", type: .Library(.Dynamic), modules: "Hummingbird")
remote:           ^~~~~~~
remote: /tmp/build_37bf4ccdf1edc5c49a72e2add8982a0f/Packages/Hummingbird-2.0.0/Package.swift:17:1: error: use of unresolved identifier 'products'
remote: products.append(lib)
remote: ^~~~~~~~
remote: swift-build: error: exit(1): ["/app/tmp/cache/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-02-08-a/usr/bin/swiftc", "--driver-mode=swift", "-I", "/app/tmp/cache/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-02-08-a/usr/lib/swift/pm", "-L", "/app/tmp/cache/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-02-08-a/usr/lib/swift/pm", "-lPackageDescription", "/tmp/build_37bf4ccdf1edc5c49a72e2add8982a0f/Packages/Hummingbird-2.0.0/Package.swift"]
remote: 
remote: Using version 0.1.0 of package SHA2
remote: 
remote:  !     Push rejected, failed to compile Swift app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to vapor-swift-lance.
remote: 
To https://git.heroku.com/vapor-swift-lance.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/vapor-swift-lance.git'

I am using DEVELOPMENT-SNAPSHOT-2016-03-24-a.

which I have no idea how to solve right now. Do you know what might be a possible cause?

**Comment by kylef** [comment]
It seems you are actually using `DEVELOPMENT-SNAPSHOT-2016-02-08-a` and not `DEVELOPMENT-SNAPSHOT-2016-03-24-a` as per version in the logs:

```
remote: -----> Installing DEVELOPMENT-SNAPSHOT-2016-02-08-a
```

The error shows, one of your dependencies is not compatible with `DEVELOPMENT-SNAPSHOT-2016-02-08-a`.

```
remote: /tmp/build_37bf4ccdf1edc5c49a72e2add8982a0f/Packages/Hummingbird-2.0.0/Package.swift:16:11: error: use of unresolved identifier 'Product'
remote: let lib = Product(name: "Hummingbird", type: .Library(.Dynamic), modules: "Hummingbird")
remote: ^~~~~~~
remote: /tmp/build_37bf4ccdf1edc5c49a72e2add8982a0f/Packages/Hummingbird-2.0.0/Package.swift:17:1: error: use of unresolved identifier 'products'
remote: products.append(lib)
```
