### ISSUE TITLE
Deploys failing on latest update

### ISSUE THREAD

**Issue by LoganWright** [kylef/heroku-buildpack-swift#9]
Hi Kyle,

First, thanks so much for the buildpack! It has made getting setup on Heroku a breeze and been very awesome to work with.

I'm worried that commit <a href="https://github.com/kylef/heroku-buildpack-swift/commit/b6d6c6d962ee0476c33542b9baf77e36cbb5c3b5">b6d6c6</a> might have introduced a bug. Or perhaps there's some new requirements I'm not fulfilling. 

Here's an example error output:

```
-----> Copying dynamic libraries
cp: cannot stat ‘/tmp/build_a7bfb1498876ce5899a7c598f604aa16/.build/release/*.so’: No such file or directory
 !     Push rejected, failed to compile Swift app
```

And a link to the original issue that was brought to my attention on my repo <a href="https://github.com/qutheory/vapor/issues/248">here.</a>

Let me know if I can help

Thanks again!

**Comment by briancroom** [comment]
Hi @LoganWright, I believe the culprit commit+line here is actually https://github.com/kylef/heroku-buildpack-swift/commit/5a694fda377fd9ff807f61c8666a369a70bab2d6#diff-c7b43338c09c3c9afd420fd8b6bb5198R63 as this command actually fails if the glob pattern does not match any files. 

When I opened a PR for the Cloud Foundry fork of this buildpack to merge in recent upstream improvements, I adjusted that command to be more robust, like this: https://github.com/cloudfoundry-community/swift-buildpack/pull/13/files#diff-c7b43338c09c3c9afd420fd8b6bb5198R75

I would suggest trying that same change here and opening a PR if it resolves the issue for you!

**Comment by LoganWright** [comment]
@briancroom Your suggestions worked on my fork, and I put the PR back into this repo. Thank you! Let's see what Kyle has to say about it.
